### ISSUE TITLE
typo: decalration

### ISSUE THREAD

**Issue by 1and1get2** [android/kotlin-guides#25]
Whitespace -> Horizontal -> 5.  declaration

**Comment by 1and1get2** [comment]
also, this this section (https://android.github.io/kotlin-guides/style.html#type-names)
Interface names may also be nouns or noun phrases (for example, List), but ~~~my~~~may sometimes be adjectives or adjective phrases instead (for example Readable).

**Comment by 1and1get2** [comment]
[see pull request 26](https://github.com/android/kotlin-guides/pull/26)

**Comment by JakeWharton** [comment]
Merged the fix.
