### ISSUE TITLE
Using expression functions.

### ISSUE THREAD

**Issue by makovkastar** [android/kotlin-guides#40]
The [style guide](https://android.github.io/kotlin-guides/style.html#expression-functions) says that expression functions should not wrap to two lines. But the IDE inspection suggests that even multi-line functions with a single expression should be converted to an expression function:

<img width="824" alt="screen shot 2017-11-20 at 14 07 58" src="https://user-images.githubusercontent.com/1076309/33019938-a251ee82-cdfc-11e7-9f1b-a0bd50585f04.png">

**Comment by JakeWharton** [comment]
As you said, this is a _multi-line statement_ but is not a statement that is being **forced to wrap**. Thus, it is valid as an expression body in the form
```kotlin
override fun convert(from: String) = when (from) {
    "N" -> ChargingStatus.Mode.NOT_CONNECTED
    ...
}
```

**Comment by makovkastar** [comment]
Thank you, now it's clear. Closing the issue.

**Comment by JakeWharton** [comment]
Dupe #36.
